# Generated by Django 3.2.20 on 2023-08-02 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='tes', max_length=200, verbose_name='Страница продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpost',
            name='products_count',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
