# Generated by Django 3.2.20 on 2023-08-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230803_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='w', max_length=200, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default=4, max_length=200, verbose_name='скидка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='w', max_length=200, verbose_name='Изображение товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=3, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
