# Generated by Django 3.2.20 on 2023-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230804_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(max_length=200, null=True, verbose_name='скидка'),
        ),
    ]
